EpikCord/EpikCord.py

EpikCord/embed.py

Some stuff here to note:-
1. changing this can improve the efficiency of our users as ,if we had used the dict way.Our programmer wont even know the keys to input. example :they might think that the key for changing timestamp is "time".
2. The American English uses the spelling "color" while brits use "colour" so people might expect colour to be the key
So i made these changes to reflect that

change params to kwargs instead of dict in  embed

---

README.md

Since GitHub flavored markdown doesn't support iframe tags, replace the iframe tag in the README with a Discord server badge from shields.io

Remove iframe tag, add Discord badge

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

* Added a template for pull requests
* Added a template for feature request issues
* Added a template for bug request issues
* Blank issues are no longer allowed

Add issue templates and pull request templates

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/PULL_REQUEST_TEMPLATE.md
EpikCord/__init__.py
EpikCord/managers/guildsmanager.py
EpikCord/managers/rolemanager.py

Fix some "not defined" messages

Fix bugs and get ready for release

---

EpikCord/__init__.py
EpikCord/managers/__init__.py

Refactor code making it more shorter and less complex
- [] - All code changes have been tested, if any
- [] - The documentation has been updated accordingly for any code changes
- [] - This PR fixes an already existing issue
- [] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [] - This PR fixes a bug
- [] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)
This is not in the checklist above and I haven't tested the code so you might wanna test first (I can't because I don't have much time)

Refactor code

---

EpikCord/__init__.py

Login function
Do not merge - I say this should be a draft we need to test this out first

Make login for bot

---

EpikCord/__init__.py
setup.py

Just add some few major and minor improvements like implement :class:  StickerItem and improve setup.py

Inch more closer to production

---

EpikCord/__init__.py

A loop cleaner for login function so it doesn't raise an error

Add loop cleaner

---

.github/workflows/bandit.yml
.github/workflows/codespell.yml
EpikCord/__init__.py
EpikCord/managers/__init__.py
EpikCord/managers/interaction_option_resolver.py

Fix grammar and add workflows

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
EpikCord/__init__.py

I have finished adding dict.get(KEY) @TheUntraceable

data.get more stuff & fix bugs (tedious)

---

EpikCord/__init__.py

Added more colors to class Colour - lightmode, darkmode, blurple_old and blurple_new. Closes #14.
N/A

Add lightmode, darkmode, blurple_old and blurple_new to the Colour class

---

EpikCord/__init__.py
EpikCord/__main__.py
setup.py

Bump version to 0.4.9 to adhere to semantic versioning

---

examples/message.py

@TheUntraceable  I copied half of your code

Add an example

---

setup.py

I implemented requirements.py into setup.py

Implement requirements.py into setup.py

---

.github/workflows/pypi_auto_release.yml
docs/source/conf.py
docs/source/index.rst
docs/source/logging.rst

Docs improve

---

EpikCord/__init__.py
docs/source/conf.py
docs/source/logging.rst

I added some of docstrings + added support 4 it

Add support for autodoc a.k.a docstrings + add docstrings

---

docs/source/conf.py

fix docstring not deploying (hopefully)

---

.github/workflows/pypi_auto_release.yml

Fix Pyautorelease not woking (maybe) #93

---

EpikCord/__init__.py
README.md

Fix things

---

.github/ISSUE_TEMPLATE/feature_request.yml

Fix useless checklist in feature request template

---

EpikCord/components.py

Fix codespell checks

---

EpikCord/__init__.py
EpikCord/managers/member_manager.py

Current state

---

EpikCord/__init__.py

Do basic voice stuff, adding all later

feat:  basic voice implementation

---

EpikCord/__init__.py

This PR changes from `+=` to `|=`, because `|=` works on binary-basis and this is what you should use for discord flags.
Also |= does not change value if it already has value, for example
`a = 0`
`a |= 1 << 0`
`print(a) # 1`
`a |= 1 << 0`
`print(a) # 1`
- [ x] - All code changes have been tested, if any
- [ x] - This PR fixes a bug

Use proper operation for permissions and intents

---

EpikCord/__init__.py

- [x ] - All code changes have been tested, if any
- [ x] - This PR fixes an already existing issue
- [ x] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ x] - This PR fixes a bug

Handle flags a bit better

---

EpikCord/__init__.py
EpikCord/components.py
EpikCord/managers/channel_manager.py
EpikCord/options.py
docs/source/conf.py
examples/slash_commands.py

- Improving option registration by using dicts instead of elifs chain.
- Tiny improvements for better code readability 
- Removed some useless white-spaces

:recycle: Improving option registration

---

.gitignore
examples/basic_bot.py
examples/message.py
examples/message_commands.py
examples/slash_commands.py
examples/user_commands.py

Updating all old example bots intents that were not working due to breaking changes
**Warning** This fix one error of the example bots but not all.

:recycle: Fixing example Bots intents

---

EpikCord/__init__.py
EpikCord/__main__.py
EpikCord/components.py
EpikCord/managers/__init__.py
EpikCord/managers/channel_manager.py
EpikCord/managers/guilds_manager.py
EpikCord/managers/member_manager.py
EpikCord/options.py
EpikCord/partials.py

Yet again some little code change to improve speed or pythonicity

:zap: Small improvements

---

EpikCord/options.py

I saw code where Union[x] where x != None was used while being set to None as default, so this PR adds Optional to them.

Fix some typehint

---

EpikCord/__init__.py

Used defaultdict to avoid try/except blocks

:recycle: Improved the EvenHandler with defaultdict

---

EpikCord/__init__.py
EpikCord/__main__.py
docs/conf.py

:recycle: Rewrote Paginator

---

.github/workflows/black.yml

Add Black formatter as github action

:construction_worker: Added black formatter within CI

---

EpikCord/__init__.py
EpikCord/__main__.py
EpikCord/components.py
EpikCord/options.py
examples/message.py

:recycle: A bunch of small fixes

---

EpikCord/__init__.py
EpikCord/components.py
EpikCord/options.py

:recycle: More Fixes

---

EpikCord/__init__.py
docs/source/conf.py

command_error event

---

EpikCord/__init__.py
EpikCord/close_event_codes.py
EpikCord/opcodes.py
EpikCord/options.py

mostly modifying comments and docstring as well as adding type hints
also removes the try/except in 
in `/__init__.py`
- added type hints in some places
- modified comments to make them look good with Better Comments
- modified `ClientUserCommand` docstring to reflect types
in `/close_event_codes.py`
- moved universal Event Codes to `CloseEventCode` base class
in `/opcodes.py`
- changed `pass` to Ellipsis  shorthand in `OpCode` because it looks better
in `/options.py`
- modified comments for BetterComments Extension
It's mostly style changes tbh however it is not NOT a code change so most of the checklist doesn't apply
As for code changes its mostly just find_spec that's now in there

use find_spec instead try/except, small changes

---

EpikCord/__init__.py
EpikCord/channels.py
EpikCord/client/event_handler.py
EpikCord/ext/tasks.py
EpikCord/rtp_handler.py

Remove useless imports
Improved code & refactored some bits

:recycle: Refactor and cleanup

---

EpikCord/__init__.py
EpikCord/flags.py
examples/basic_bot.py
examples/message_commands.py
examples/slash_commands.py
examples/user_commands.py

moves flags (intent, permissions, systemchannelflags) into separate file
and an issue fix, probably

some stuff

---

EpikCord/flags.py

Signed-off-by: sigmanificient <edhyjox@gmail.com>
:recycle: Replaced Flag with std enum.IntFlag custom subclass

:recycle: Replaced Flag with std enum.IntFlag custom subclass

---

EpikCord/application/application.py

- `Optional` for flags as its ommitable
- `[item]` for when it is "guaranteed"
- `Class([item]) if item in data` for when it is a nullable/ommittable object
- `List[str]` to represent the type of items

fix(application): use correct attribute typehints

---

.dmypy.json
.gitignore

:fire: Delete .dmypy.json

---

EpikCord/abstract.py

Signed-off-by: sigmanificient <edhyjox@gmail.com>

:recycle: idk what TheUntraceable did here

---

.github/workflows/black.yml

Welp workflows is working for main branch, here the fix

:pencil: Somehow we are still using "master" branch
